---
# An Ansible Playbook to backup the Mikrotik device's configuration to both script and backup file
# Version 1 - 07/01/2017
#
# ansible.cfg
# [paramiko_connection]
# pty=False
#
- name: Mikrotik Backup Device Configuration
  hosts: server
  connection: paramiko
  user: root
  gather_facts: no
  tasks:
   - name: Backup Firewall
     raw: df -h
   - name: Exporting Firewall
     raw: ps a
